
export const ActionTypes = {
  USER_SIGNUP: 'USER_SIGNUP',
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',

  FETCH_PROFILE: 'FETCH_PROFILE',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_ERROR: 'FETCH_PROFILE_ERROR',

  FETCH_WALLETS: 'FETCH_WALLETS',
  FETCH_WALLETS_SUCCESS: 'FETCH_WALLETS_SUCCESS',
  FETCH_WALLETS_ERROR: 'FETCH_WALLETS_ERROR',

  FETCH_TASKS: 'FETCH_TASKS',
  FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
  FETCH_TASKS_ERROR: 'FETCH_TASKS_ERROR',

  VERIFY_WALLET: 'VERIFY_WALLET',
  VERIFY_WALLET_SUCCESS: 'VERIFY_WALLET_SUCCESS',
  VERIFY_WALLET_ERROR: 'VERIFY_WALLET_ERROR',


}
